traffic light:
  X_w: 0
  Y_w: 0
  Z_w: 0
  size: 0.1
  obstacle: true
bulb:
  X_w: 2.342521
  Y_w: 0.3572852
  Z_w: 1.240931
  size: 0.15
  obstacle: false
cctv:
  X_w: 0
  Y_w: 0
  Z_w: 0
  size: 0.05
  obstacle: true